### ISSUE TITLE
Fix function example ( [delta]t instead of t)

### ISSUE THREAD

**Issue by VineBoomSoundEffect** [greg-bt/DeltaTime#1]
Thank you a lot for making this repository! It was very helpful, an eye opener if you will. There is only a minuscule problem in the function example, where instead of `return Δt`, there is `returnt`. It's not such deep of a problem, I simply noticed it. I'll leave you to correct it, if you'd like.

**Comment by greg-bt** [comment]
Absolute no worries, honestly never thought this repo would be seen by anyone other than myself but I'm glad you found it helpful!

**Comment by greg-bt** [comment]
Typo fixed.
